name: Quickstart

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist

    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit

    - name: Execute PHPBF
      run: vendor/bin/phpcbf --standard=PSR12 src/

    - name: Execute PHPCS
      run: vendor/bin/phpcs --standard=PSR12 src/

      # static analysis

      # cs-fixer solve issues
